// module.exports.descriptors = [
//     'Cozy',
//     'Charming',
//     'Modern',
//     'Spacious',
//     'Renovated',
//     'Quaint',
//     'Elegant',
//     'Stylish',
//     'Rustic',
//     'Contemporary',
//     'Historic',
//     'Sleek',
//     'Bright',
//     'Sunny',
//     'Welcoming',
//     'Serene',
//     'Inviting',
//     'Tranquil',
//     'Picturesque',
//     'Immaculate'
// ]
module.exports.details=[
   "Indulge in the ultimate beachfront escape at this serene coastal retreat. With panoramic ocean views from every window, direct access to sandy shores, and the soothing sound of waves crashing, this home is a paradise for beach lovers. Relax on the private balcony, watch stunning sunsets over the water, and let the coastal breeze rejuvenate your senses.",
   "Experience mountain living at its finest in this charming alpine chalet. Nestled among towering peaks, this cozy retreat offers panoramic views, a crackling fireplace to cozy up by, and convenient access to nearby hiking trails and ski slopes. Whether you're seeking outdoor adventure or simply a tranquil mountain getaway, this chalet is the perfect home base.",
   "Discover an urban oasis in the heart of the city at this stylish and modern home. With sleek design, luxurious amenities, and proximity to the vibrant city center, this home provides a perfect balance between urban excitement and private relaxation. Unwind in the rooftop garden, savor gourmet meals in the chef's kitchen, and immerse yourself in the city's cultural and entertainment offerings.",
   "Escape to the picturesque countryside and experience the charm of this restored farmhouse. Surrounded by rolling hills and blooming fields, this tranquil retreat offers a true escape from the hustle and bustle of city life. Embrace the simplicity of country living, enjoy lazy afternoons in the expansive garden, and immerse yourself in the beauty of nature, making lasting memories with loved ones.",
   "Retreat to a cozy cottage with stunning lake views, nestled in a peaceful lakeside community. Wake up to the shimmering waters just steps away from your doorstep, enjoy a morning coffee on the private deck, and embark on exciting water activities. Whether you're fishing, kayaking, or simply enjoying a lakeside picnic, this cottage offers a serene and idyllic setting for a memorable vacation.",
   "Experience the epitome of urban chic in this stunning loft apartment. With its contemporary design, open-concept layout, and floor-to-ceiling windows showcasing city views, this space exudes modern luxury. Relax in the designer furnishings, whip up gourmet meals in the fully equipped kitchen, and indulge in the vibrant city life just beyond your doorstep, making it a perfect choice for cosmopolitan adventurers.",
   "Fulfill your childhood dreams with a stay in this enchanting treehouse retreat. Nestled among towering trees, this whimsical abode offers a unique and magical experience. Relax on the suspended balcony, listen to the sounds of nature, and enjoy the panoramic views of the surrounding forest. Disconnect from the world and reconnect with your inner child in this extraordinary treetop sanctuary.",
   "Embrace the rustic charm of a lakeside cabin, perched on the edge of a tranquil lake. With its warm wood interiors, stone fireplace, and private dock, this cozy retreat invites you to relax and unwind. Spend your days swimming, fishing, or simply soaking in the serene beauty of the surroundings. As the sun sets over the water, gather around the fire pit for a memorable evening under the starry sky.",
   "Immerse yourself in the untouched wilderness with a stay at this secluded lodge. Accessible only by boat or hiking, this off-the-grid retreat offers a true escape from civilization. With breathtaking nature views, hiking trails at your doorstep, and the soothing sounds of wildlife, this lodge is a haven for nature lovers seeking tranquility and solitude.",
   "Step back in time and experience the grandeur of a meticulously restored historic manor. Adorned with period furnishings, elegant architecture, and rich history, this home offers a glimpse into the past. Enjoy afternoon tea in the lush gardens, explore the intricately designed rooms, and create your own memories within the walls of this magnificent estate.",
   "Unwind in a luxurious desert retreat, surrounded by vast arid landscapes and breathtaking sunsets. This modern oasis offers a private pool, spacious outdoor lounge areas, and panoramic views of the desert. Immerse yourself in the serenity of the desert, stargaze under clear skies, and discover the beauty of this unique environment.",
   "Escape to an exclusive island paradise where turquoise waters meet pristine white sands. This private villa boasts luxurious amenities, private beach access, and stunning ocean views. Dive into crystal-clear waters, unwind in a hammock beneath swaying palm trees, and indulge in the ultimate tropical getaway.",
   "Experience the ultimate winter retreat with a ski-in/ski-out chalet nestled in a picturesque alpine village. Enjoy direct access to the slopes, luxurious hot tubs with mountain views, and cozy evenings by the fireplace. This chalet is the perfect base for avid skiers and snowboarders seeking the thrill of fresh powder and unforgettable mountain adventures.",
   "Discover the epitome of luxury in a sprawling coastal mansion. Boasting expansive ocean-facing balconies, a private pool, and impeccable interior design, this estate offers a lavish escape. Bask in the sun by day, savor gourmet meals prepared in the chef's kitchen, and experience coastal living at its finest.",
   "Step into history with a stay in a meticulously restored historic townhouse. Located in the heart of a charming town, this elegantly furnished home offers a unique blend of modern comfort and vintage charm. Explore nearby landmarks, stroll through cobblestone streets, and immerse yourself in the rich heritage of the area.",
]
module.exports.houseName = [
    'Hillside',
    'Retreat',
    'Haven',
    'Cottage',
    'Hideaway',
    'Lodge',
    'Nest',
    'Residence',
    'Abode',
    'Oasis',
    'Estate',
    'Villa',
    'Manor',
    'Bungalow',
    'Homestead',
    'Sanctuary',
    'Refuge',
    'Getaway',
    'Dwelling',
    'Housing',
    'Resort'
]